---
title: "Account Timeline Data"
author: "Ryan Johnson"
date: "11/18/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(odbc)
library(DBI)
library(dbplyr)
library(pins)
library(scales)
library(warehouse)
```

# Setup connections
```{r}
# RStudio Data Warehouse
con <- lakehouse()

# Register Pin Board
board <- board_rsconnect(server = Sys.getenv("CONNECT_SERVER"))
```

# Extract Account and Opp information
```{r}
# Get Account names
account_info <- tbl(con, in_schema("salesforce_v1", "account")) %>%
  filter(is_deleted == "0") %>% 
  filter(type == "Customer") %>% 
  collect() %>% 
  select(acct_id = id, acct_name = name,
         acct_cs_owner_id = customer_success_team_member_c,
         acct_owner_id = owner_id,
         acct_pod = pod_team_c)

# Get Rep ID and name
reps <- tbl(con, in_schema("salesforce_v1", "user")) %>%
  select(first_name, last_name, id) %>% 
  collect() %>% 
  unite("rep_name", c("first_name", "last_name"), sep = " ") %>% 
  rename(owner_id = id)

# Get Opps
opps <- tbl(con, in_schema("salesforce_v1", "opportunity")) %>% 
  filter(is_deleted == "0") %>%
  filter(!stage_name %in% c("Opportunity Disqualified")) %>% 
  filter(account_id %in% !!account_info$acct_id) %>% 
  collect() %>% 
  select(opp_id = id, 
         acct_id = account_id, 
         opp_name = name, 
         opp_stage = stage_name,
         opp_amount = amount,
         opp_close_date = close_date,
         opp_type = type,
         opp_products = product_interest_c,
         license_start_date = license_start_date_c,
         license_end_date = license_end_date_c,
         opp_closed_lost_details = closed_lost_details_c,
         opp_closed_won_details = closed_won_details_c,
         opp_deal_summary = deal_summary_c,
         opp_next_steps = next_steps_c) %>%
  mutate(opp_amount = dollar(opp_amount)) %>% 
  mutate(opp_summary = glue::glue('### {opp_name}\r\n* **{opp_stage} - {opp_type}**\r\n\n* **Close Date**: {opp_close_date}\r\n\n* **Opp Amount**: <span style="color:green">{opp_amount}</span>\r\n#### Products\r\n{opp_products}\r\n##### Closed Won Details\r\n{opp_closed_won_details}\r\n##### Closed Lost Details\r\n{opp_closed_lost_details}\r\n##### Deal Summary\r\n{opp_deal_summary}\r\n##### Next Steps\r\n{opp_next_steps}\n\n'))

# Create final opp table
opp_final <- opps %>% 
  select(event_subtype = opp_stage,
         event_date = opp_close_date,
         event_label = opp_type,
         event_notes = opp_summary,
         event_acct_id = acct_id) %>%
  mutate(event_type = "Sales") %>% 
  select(event_type, event_subtype, everything())
```

# Get Call Data
```{r}
# Get call notes
calls <- dplyr::tbl(con, in_schema("salesforce_v1", "task")) %>%
  filter(account_id %in% !!account_info$acct_id) %>%
  # Select all calls from both CS and Sales
  filter(owner_id %in% !!unique(c(account_info$acct_cs_owner_id, account_info$acct_owner_id))) %>%
  select(
    call_id = id,
    call_subject = subject,
    call_what_id = what_id,
    call_date = activity_date,
    call_status = status,
    call_description = description,
    call_subtype = task_subtype,
    call_category = meeting_category_c,
    call_type = type,
    call_acct_id = account_id,
    call_who_id = who_id,
    call_owner_id = owner_id,
    call_created_date = created_date,
    call_created_by_id = created_by_id) %>%
  mutate(label = case_when(
    (call_subtype == 'Call' & call_type == 'Call') ~ 'Call',
    !is.na(call_subtype) ~ 'Email')) %>%
  collect() %>%
  # Filter for just calls
  filter(label == "Call")

# Create final call table
calls_final <- calls %>% 
  # If logged by account owner == Sales, 
  # If logged by CS == CS
  mutate(event_type = case_when(
    call_owner_id %in% unique(account_info$acct_owner_id) ~ "Sales",
    call_owner_id %in% unique(account_info$acct_cs_owner_id) ~ "CS"
  )) %>% 
  select(event_type,
         event_subtype = call_category,
         event_date = call_date,
         event_label = call_category,
         event_notes = call_description,
         event_acct_id = call_acct_id) %>% 
  select(event_type, everything())
```


# Create merged opp + call
```{r}
opp_calls <- full_join(opp_final, calls_final) %>% 
  # add in acct info
  left_join(account_info, by = c("event_acct_id" = "acct_id")) %>% 
  # add in arbitrary x_axis for unique ggplot
  mutate(x_axis = 0)
```


# Support ticket items
```{r}
# Get support ticket pin
support_tickets <- pin_read(board, "amanda/support_tickets")

all_tickets <- support_tickets %>% 
  # filter for just support tickets
  filter(group_name == "Support") %>% 
  select(ticket_id = id,
         ticket_created = created_at,
         ticket_solved_date = solved_at,
         ticket_closed_at = closed_at,
         ticket_subject = subject,
         ticket_description = description,
         ticket_priority = priority,
         ticket_status = status, 
         ticket_account = org_name,
         ticket_requester = requester_name,
         ticket_requester_email = requester_email) %>% 
  filter(ticket_account %in% account_info$acct_name) %>% 
  mutate(ticket_label = glue::glue('Ticket: {ticket_status}')) %>%
  mutate(ticket_link = glue::glue("https://rstudioide.zendesk.com/agent/tickets/{ticket_id}")) %>% 
  mutate(ticket_summary = glue::glue('### [{ticket_id}]({ticket_link}) - {ticket_subject}\r\n**Date Opened**: {ticket_created}\r\n\n**Status**: {ticket_status}\r\n\n**Requester**: [{ticket_requester}]({ticket_requester_email})'))
  
# Final ticket data
ticket_final <- all_tickets %>% 
  select(event_subtype = ticket_status,
         event_date = ticket_created,
         event_label = ticket_label,
         event_notes = ticket_summary,
         acct_name = ticket_account) %>% 
  mutate(event_type = "Support") %>% 
  left_join(account_info, by = "acct_name") %>% 
  rename(event_acct_id = acct_id) %>% 
  mutate(event_date = lubridate::as_date(event_date)) %>% 
  select(event_type, event_subtype, event_date,
         event_label, event_notes, event_acct_id, 
         acct_name, acct_owner_id, acct_cs_owner_id) %>%
  mutate(x_axis = 0)
```

# SE Calls
```{r}
se_calls <- support_tickets %>% 
  # filter for just SE calls
  filter(group_name == "Sol-Eng") %>% 
  select(ticket_id = id,
         ticket_created = created_at,
         ticket_solved_date = solved_at,
         ticket_closed_at = closed_at,
         ticket_subject = subject,
         ticket_description = description,
         ticket_priority = priority,
         ticket_status = status, 
         ticket_account = org_name,
         ticket_requester = requester_name,
         ticket_requester_email = requester_email) %>% 
  filter(ticket_account %in% account_info$acct_name) %>% 
  mutate(ticket_label = glue::glue('Sol-Eng Call')) %>%
  mutate(ticket_link = glue::glue("https://rstudioide.zendesk.com/agent/tickets/{ticket_id}")) %>% 
  mutate(ticket_summary = glue::glue('### [{ticket_id}]({ticket_link}) - {ticket_subject}\r\n**Date Opened**: {ticket_created}\r\n\n**Status**: {ticket_status}\r\n\n**Requester**: [{ticket_requester}]({ticket_requester_email})'))
  
# Final ticket data
se_call_final <- se_calls %>% 
  select(event_subtype = ticket_status,
         event_date = ticket_created,
         event_label = ticket_label,
         event_notes = ticket_summary,
         acct_name = ticket_account) %>% 
  mutate(event_type = "SE Call") %>% 
  left_join(account_info, by = "acct_name") %>% 
  rename(event_acct_id = acct_id) %>% 
  mutate(event_date = lubridate::as_date(event_date)) %>% 
  select(event_type, event_subtype, event_date,
         event_label, event_notes, event_acct_id, 
         acct_name, acct_owner_id, acct_cs_owner_id) %>%
  mutate(x_axis = 0)
```

# Join all SE and support tickets
```{r}
se_support_all <- ticket_final %>% 
  full_join(se_call_final)
```

# Merge opp + call and tickets
```{r}
final_data <- opp_calls %>% 
  full_join(se_support_all) %>%
  # add in rep names
  left_join(reps, by = c("acct_owner_id" = "owner_id")) %>% 
  rename(acct_owner_name = rep_name) %>% 
  left_join(reps, by = c("acct_cs_owner_id" = "owner_id")) %>% 
  rename(acct_cs_owner_name = rep_name)
```


# Pin Data
```{r}
# Pin
board %>% 
  pin_write(final_data, "acct_timeline_data", type = "rds")
```

